spring.application.name=BankingSystem

# DATABASE CONFIGURATION

spring.datasource.url=${DB_URL}

spring.datasource.username=${DB_USERNAME}

spring.datasource.password=${DB_PASSWORD}

# JPA CONFIGURATION

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# SERVER PORT

server.port=8080

# JWT SECRET

jwt.secret=${JWT_SECRET}

# SWAGGER

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

# REDIS CONFIG

spring.data.redis.host=${REDIS_HOST}

spring.data.redis.port=${REDIS_PORT}