spring.application.name=BankingSystem

# DATABASE CONFIGURATION
spring.datasource.url=jdbc:postgresql://localhost:5432/banking_db

spring.datasource.username=postgres
spring.datasource.password=@Abhi_1606

# JPA CONFIGURATION
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# SERVER PORT
server.port=8080

# JWT SECRET KEY
jwt.secret=ThisIsMySecureJwtSecretKeyForBankingApplication

# SWAGGER
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

# REDIS CONFIG
spring.data.redis.host=localhost
spring.data.redis.port=6379



